trigger:
- master

variables:
- name: emailAddress
- value: user123@demo.com
  readonly: true
- name: userName
- value: John Doe
  readonly: true

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   git config --global user.email $(emailAddress) $ git config --global user.name $(userName)
  workingDirectory:  $(System.DefaultWorkingDirectory)

-script: |
  git checkout -b main
  echo 'This is a test' > test-file.txt
  git add -A
  git commit -m "deployment $(Build.BuildNumber)"
  git push --set-upstream origin master
  displayName: Add test file
workingDirectory: $(System.DefaultWorkingDirectory)
