trigger:
- master

variables:
- group: vg-test # Add your own variable group name
- name: emailAddress
  value: $(git-email-address)
- name: userName
  value: $(git-user-name)

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
   git config --global user.email $(emailAddress) & git config --global user.name $(userName)
  workingDirectory:  $(System.DefaultWorkingDirectory)

- script: |
   git checkout -b master
   echo 'This is a test' > test-file.txt
   git add -A
   git commit -m "deployment $(Build.BuildNumber)"
   git push --set-upstream origin master
  displayName: Add test file
  workingDirectory: $(System.DefaultWorkingDirectory)
